### ISSUE TITLE
gamps-web-sync doesn't work on MacOS

### ISSUE THREAD

**Issue by jgtimm** [DavidMStraub/gramps-web-sync#26] opened 2024-02-19 21:42 UTC
This plugin does not work with MacOS, tested with self hosted Web Gramps Backend and identical Configuration on MacOS and Windows: It does work with Gramps on Windows, fails with "Fehler beim Zugriff auf den Server.". 
There is a discussion on this Issue here: https://gramps.discourse.group/t/debugging-connection-issue-with-gramps-web-sync-on-mac/4604 but the discussion quickly derailed on how this bug could be debugged with no solution in sight.

Versions used to reproduce:
MacOS Sonoma 14.3.1 with Gramps 5.1.6, Plugin 1.1.1: Does not works
Windows 10 with Gramps 5.1.6, Plugin 1.1.1: Works
Gramps Web: Gramps 5.1.6, Gramps Web API 1.6.0, Gramps Web Frontend 24.2.0, locale: en, multi-tree: false, task queue: true

**Comment by andreaiorio** [comment] 2024-02-25 00:15
I've been using Gramps Web and Web Sync on macOS without issues for the past 3 months on my local Gramps app. Therefore, I disagree with the claim that the app doesn't work on macOS in general.

However, I am experiencing the issue described in the linked discussion when trying to sync to the same app accessed through a Cloudflare tunnel using a DNS record for the tunnel endpoint. This is despite the app having an SSL certificate (potentially related to issue #24?). Localhost syncing works perfectly fine.

I believe that – at least in my case – the issue is originating from line 64 `with urlopen(req) as res:` in `webapihandler.py`.

Versions:

- macOS: Sonoma 14.2.1
- Gramps: 5.2
- Plugin: 1.0.3 (both stable and developer versions)

**Comment by DavidMStraub** [comment] 2024-02-25 10:07
Thanks @andreaiorio, that's valuable information.

Did you check whether the fix suggested in #24 works for you?

**Comment by andreaiorio** [comment] 2024-02-25 12:39
Unfortunately, that trick does not work in my case. It still returns a generic `urllib.error.HTTPError: HTTP Error 403: Forbidden`.

**Comment by DavidMStraub** [comment] 2024-02-25 12:41
But 403 means it's a permissions error, it can't be due to connection issues. Perhaps you mistyped the password or don't have owner permissions?

**Comment by andreaiorio** [comment] 2024-02-25 13:03
The password is correct, but I am not sure about the owner's permissions. The 403 error is given by this minimal code I was trying outside Gramps with the remote url:

```python
from urllib.request import Request, urlopen
import json, ssl

ctx = ssl.create_default_context()
ctx.check_hostname = False
ctx.verify_mode = ssl.CERT_NONE

username = "username"
password = "password"
url = "https://remote_url.com"
# url = "http://localhost" # the same code with localhost works correctly
data = json.dumps({"username": username, "password": password})
req = Request(f"{url}/api/token/", data=data.encode(), headers={"Content-Type": "application/json"})
res = urlopen(req)
print(json.load(res))
```

While trying inside Gramps with this `webapihandler.py`:
```python
    def fetch_token(self) -> None:
        """Fetch and store an access token."""
        data = json.dumps({"username": self.username, "password": self.password})
        req = Request(
            f"{self.url}/token/",
            data=data.encode(),
            headers={"Content-Type": "application/json"},
        )
        try:
            _LOG.debug("Before request")
            with urlopen(req, context=ctx) as res:
                _LOG.debug("Inside request")
                _LOG.debug(json.load(res))
                res_json = json.load(res)
        except (UnicodeDecodeError, json.JSONDecodeError, HTTPError):
            _LOG.debug("Inside except")
            if "/api" not in self.url:
                self.url = f"{self.url}/api"
                return self.fetch_token()
            raise
        self._access_token = res_json["access_token"]
```

The log only returns:
```
2024-02-25 13:52:29.440: DEBUG: webapihandler.py: line 72: Before request
2024-02-25 13:52:29.627: DEBUG: webapihandler.py: line 78: Inside except
2024-02-25 13:52:29.628: DEBUG: webapihandler.py: line 72: Before request
2024-02-25 13:52:29.739: DEBUG: webapihandler.py: line 78: Inside except
```

**Comment by andreaiorio** [comment] 2024-02-25 14:48
I encountered two issues:

- Cloudflare was blocking requests until I added a User-Agent header: `"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"`. It's unclear if this is a viable solution or if it should be handled on the server-side.
- Requests are still failing to verify the SSL certificate, even though it's valid. Disabling SSL checks, as suggested in issue #24, would resolve this. This issue might be related to a [known problem](https://stackoverflow.com/a/42334357) with Python on macOS, where it requires a post-installation step to validate SSL connections and could potentially affect all macOS users who are not working on localhost.

**Comment by jgtimm** [comment] 2024-02-25 17:26
Well, after the comments from @andreaiorio I tried a couple of things: 

- Installed the newest Python Version an ran the SSL Certificate fix. (Does Gramps even use a System installed Python or does it bring its own?) 
- My Main Mac is on Gramps 5.2 since it was released, so I did fresh install on a second Mac (also Sonoma 14.3.1) with Gramps 5.1.6 and a fresh Python install with the SSL Certificates Fix. Did not change the Problem.
- Again, as the Sync is working from Windows on a VM on the first Mac with the same credentials I think I can rule out any network problem or password typo

Is the anything I could do to help debug this? I am not a Python programmer, but I some one can provide a version of the plugin with debug / logging statement I'm happy to try it out

**Comment by andreaiorio** [comment] 2024-02-25 20:53
@jgtimm I'm afraid that Gramps uses its own Python interpreter and dependencies, and not the system one, so you don't see any change.

Providing more insights:
```python
ctx = ssl.create_default_context()
ctx.load_default_certs()
print(ssl.get_default_verify_paths())
```
It prints:
```python
DefaultVerifyPaths(cafile=None, capath=None, openssl_cafile_env='SSL_CERT_FILE', openssl_cafile='/Users/john/Development/gramps-tarball-11-arm64/inst/etc/ssl/cert.pem', openssl_capath_env='SSL_CERT_DIR', openssl_capath='/Users/john/Development/gramps-tarball-11-arm64/inst/etc/ssl/certs')
```
I don't know where SSL is retrieving the `openssl_cafile` and `openssl_capath` locations (John, reveal yourself!), but they are not mine, and hence SSL fails verifying certificates.

Adding this at the beginning of `webapihandler.py`:
```python
def create_macos_ssl_context():
    import subprocess
    import ssl
    import tempfile

    ctx = ssl.create_default_context()
    macos_ca_certs = subprocess.run(
        [
            "security",
            "find-certificate",
            "-a",
            "-p",
            "/System/Library/Keychains/SystemRootCertificates.keychain",
        ],
        stdout=subprocess.PIPE,
    ).stdout

    with tempfile.NamedTemporaryFile("w+b") as tmp_file:
        tmp_file.write(macos_ca_certs)
        ctx.load_verify_locations(tmp_file.name)
    return ctx

ctx = create_macos_ssl_context()
```
Then using the `ctx` context in `urlopen` solves the issue for me. I'm not sure if this solution is the best, but it has been recommended [here](https://stackoverflow.com/a/70054211). I feel this SSL problem could be quite widespread, like also [here](https://github.com/gramps-project/gramps-web/discussions/375).

**Comment by DavidMStraub** [comment] 2024-02-26 07:14
There is no 5.2.0 compatible version of Gramps Web yet!! Please stick with 5.1.6 for the moment.

https://www.grampsweb.org/setup/v2/

**Comment by andreaiorio** [comment] 2024-02-27 19:55
I also tested with Gramps 5.1.6 and plugin version 1.0.3, and I confirm to have no issues on Mac after implementing my fix.

@jgtimm a 200 status is indeed okay. What other issues are you experiencing? I'm happy to try to help!
@DavidMStraub should I open a PR with my edits?

**Comment by DavidMStraub** [comment] 2024-02-27 19:58
Hi, I would be very happy about a PR, the only thing I didn't quite understand is, wouldn't this affect users on other architectures? So we would only apply the fix based on `platform.system()`?

**Comment by jgtimm** [comment] 2024-03-10 19:57
Hi, today I was able to test the new versions of Gramps (5.2.0), Grampsweb (API 2.0.0, Frontend 24.3.0) and gramps-web-sync (1.1.1) on my Mac Intel with Sonoma 14.3.1. The Synchronization now works flawlessly!

**Comment by DavidMStraub** [comment] 2024-03-10 20:03
Awesome! I guess we can close this then :tada:

**Closed by DavidMStraub** 2024-03-10 20:03 UTC
